title: The Musings of Yefim Vedernikoff
productName: Version HD de la photo 
productDescription: Version HD de la photo
productPrice: "10.00"
twitter_username: johndoe
github_username: johndoe
email: john@doe.com
baseurl: /
url: https://surfoto.ifrance.net
snipcartKey: "YzA2MGMyMDQtOGEyZC00MTRhLTljMDYtNGQ1ZGFiZTYxNmZhNjM2OTkzNDY1MTE1NDYxMzgz"
exclude:
  - vendor
